spring:
  application:
    name: user-microservice-web
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: dev
        group: DEFAULT_GROUP
        metadata:
          version: 1.0.0
  redis:
    database: 2
    host: 127.0.0.1
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
    timeout: 100ms
server:
  port: 10000
dubbo:
  cloud:
    subscribed-services: "user-microservice-provider"
  registry:
    address: nacos://127.0.0.1:8848
  protocol:
    port: -1
    name: dubbo
security:
  oauth2:
    client:
      client-id: user-microservice-web
      client-secret: 123456
      user-authorization-uri: http://127.0.0.1:9098/oauth/authorize
      access-token-uri: http://127.0.0.1:9098/oauth/token
    resource:
      id: user-client
      user-info-uri: user-info
    authorization:
      check-token-access: http://127.0.0.1:9098/oauth/check_token