# 开启 shutdown endpoint
management:
  endpoints:
    web:
      exposure:
        include: 'shutdown,health'
  endpoint:
    shutdown:
      enabled: true
spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
  application:
    name: user-microservice-web
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: a6f54f4a-1768-4847-bfcd-8cb00367c586
        group: DEFAULT_GROUP
#        metadata:
#          version: 1.0.0
  redis:
    database: 2
    host: 127.0.0.1
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
    timeout: 100ms
server:
  port: 10000
  shutdown: graceful
dubbo:
  cloud:
    subscribed-services: "user-microservice-provider"
  registry:
    address: nacos://127.0.0.1:8848
  protocol:
    port: -1
    name: dubbo
security:
  oauth2:
    client:
      client-id: ${spring.application.name}
      client-secret: 123456
      user-authorization-uri: http://127.0.0.1:9098/oauth/authorize
      access-token-uri: http://127.0.0.1:9098/oauth/token
    resource:
      id: user-client
      user-info-uri: user-info
    authorization:
      check-token-access: http://127.0.0.1:9098/oauth/check_token