spring:
  application:
    name: base-microservice-web
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: a6f54f4a-1768-4847-bfcd-8cb00367c586
        group: DEFAULT_GROUP
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    time-zone: "Asia/Shanghai"
    defaultPropertyInclusion: NON_NULL
  redis:
    database: 3
    host: 127.0.0.1
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
    timeout: 100ms
server:
  port: 11000
dubbo:
  cloud:
    subscribed-services: "base-microservice-provider"
  registry:
    address: nacos://127.0.0.1:8848
  protocol:
    port: -1
    name: dubbo