spring:
  application:
    name: base-microservice-web
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: dev
        group: DEFAULT_GROUP
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    time-zone: "Asia/Shanghai"
    defaultPropertyInclusion: NON_NULL
server:
  port: 11000
dubbo:
  cloud:
    subscribed-services: "base-microservice-provider"
  registry:
    address: nacos://127.0.0.1:8848
  protocol:
    port: -1
    name: dubbo