spring:
  application:
    name: user-microservice-provider
  profiles:
    active: dev
server:
  port: 10001
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/base_cloud?serverTimezone=Asia/Shanghai
    username: root
    password: "123456"
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: a6f54f4a-1768-4847-bfcd-8cb00367c586
        group: DEFAULT_GROUP
dubbo:
  cloud:
    subscribed-services: "*"
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://127.0.0.1:8848
  scan:
    base-packages: com.zhujunji.user.service
mybatis:
  mapper-locations: classpath*:mapper/*.xml
