server:
  port: 7070
spring:
  application:
    name: gateway
  profiles:
    active: dev
logging:
  config: classpath:logback.xml
  level:
    org.springframework.cloud.gateway: debug
management:
  endpoint:
    health:
      show-details: always
---
spring:
  application:
    name: gateway
  cloud:
    gateway:
      enabled: true
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: a6f54f4a-1768-4847-bfcd-8cb00367c586
        group: DEFAULT_GROUP
      config:
        enabled: true
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
        namespace: a6f54f4a-1768-4847-bfcd-8cb00367c586
        group: ${spring.application.name}
        prefix: ${spring.application.name}
        file-extension: yaml
        refresh-enabled: true
        extension-configs[0]:
          data-id: ${spring.application.name}-sentinel.json
          group: ${spring.application.name}
    sentinel:
      enabled: true
      # 是否提前触发 Sentinel 初始化
      eager: true
      filter:
        enabled: false
      transport:
        dashboard: 127.0.0.1:7200
        client-ip: 127.0.0.1
      datasource:
        ds:
          nacos:
            username: nacos
            password: nacos
            file-extension: json
            namespace: a6f54f4a-1768-4847-bfcd-8cb00367c586
            server-addr: ${spring.cloud.nacos.discovery.server-addr}
            data-id: ${spring.application.name}-sentinel.json
            group-id: ${spring.application.name}
            rule-type: gw-flow
  config:
    activate:
      on-profile: dev
dubbo:
  cloud:
    subscribed-services: "user-microservice-web"
  registry:
    address: nacos://127.0.0.1:8848
  protocol:
    port: -1
    name: dubbo